from app import db
from flask_sqlalchemy import *
from sqlalchemy import *
from sqlalchemy.orm import relationship


class Gebiete(db.Model):
    __tablename__ = "Gebiete"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    gehört_zu = db.Column(db.Integer)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return 'Gebiet {}>'.format(self.name)


class Parteien(db.Model):
    __tablename__ = "Parteien"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return 'Partei {}>'.format(self.name)


class Stimmen(db.Model):
    __tablename__ = "stimmen"

    id = db.Column(db.Integer, primary_key=True)
    p1_0 = db.Column(db.Integer)
    p1_1 = db.Column(db.Integer)
    p1_2 = db.Column(db.Integer)
    p1_3 = db.Column(db.Integer)
    p2_0 = db.Column(db.Integer)
    p2_1 = db.Column(db.Integer)
    p2_2 = db.Column(db.Integer)
    p2_3 = db.Column(db.Integer)
    p3_0 = db.Column(db.Integer)
    p3_1 = db.Column(db.Integer)
    p3_2 = db.Column(db.Integer)
    p3_3 = db.Column(db.Integer)
    p4_0 = db.Column(db.Integer)
    p4_1 = db.Column(db.Integer)
    p4_2 = db.Column(db.Integer)
    p4_3 = db.Column(db.Integer)
    p5_0 = db.Column(db.Integer)
    p5_1 = db.Column(db.Integer)
    p5_2 = db.Column(db.Integer)
    p5_3 = db.Column(db.Integer)
    p6_0 = db.Column(db.Integer)
    p6_1 = db.Column(db.Integer)
    p6_2 = db.Column(db.Integer)
    p6_3 = db.Column(db.Integer)
    p7_0 = db.Column(db.Integer)
    p7_1 = db.Column(db.Integer)
    p7_2 = db.Column(db.Integer)
    p7_3 = db.Column(db.Integer)
    p8_0 = db.Column(db.Integer)
    p8_1 = db.Column(db.Integer)
    p8_2 = db.Column(db.Integer)
    p8_3 = db.Column(db.Integer)
    p9_0 = db.Column(db.Integer)
    p9_1 = db.Column(db.Integer)
    p9_2 = db.Column(db.Integer)
    p9_3 = db.Column(db.Integer)
    p10_0 = db.Column(db.Integer)
    p10_1 = db.Column(db.Integer)
    p10_2 = db.Column(db.Integer)
    p10_3 = db.Column(db.Integer)
    p11_0 = db.Column(db.Integer)
    p11_1 = db.Column(db.Integer)
    p11_2 = db.Column(db.Integer)
    p11_3 = db.Column(db.Integer)
    p12_0 = db.Column(db.Integer)
    p12_1 = db.Column(db.Integer)
    p12_2 = db.Column(db.Integer)
    p12_3 = db.Column(db.Integer)
    p13_0 = db.Column(db.Integer)
    p13_1 = db.Column(db.Integer)
    p13_2 = db.Column(db.Integer)
    p13_3 = db.Column(db.Integer)
    p14_0 = db.Column(db.Integer)
    p14_1 = db.Column(db.Integer)
    p14_2 = db.Column(db.Integer)
    p14_3 = db.Column(db.Integer)
    p15_0 = db.Column(db.Integer)
    p15_1 = db.Column(db.Integer)
    p15_2 = db.Column(db.Integer)
    p15_3 = db.Column(db.Integer)
    p16_0 = db.Column(db.Integer)
    p16_1 = db.Column(db.Integer)
    p16_2 = db.Column(db.Integer)
    p16_3 = db.Column(db.Integer)
    p17_0 = db.Column(db.Integer)
    p17_1 = db.Column(db.Integer)
    p17_2 = db.Column(db.Integer)
    p17_3 = db.Column(db.Integer)
    p18_0 = db.Column(db.Integer)
    p18_1 = db.Column(db.Integer)
    p18_2 = db.Column(db.Integer)
    p18_3 = db.Column(db.Integer)
    p19_0 = db.Column(db.Integer)
    p19_1 = db.Column(db.Integer)
    p19_2 = db.Column(db.Integer)
    p19_3 = db.Column(db.Integer)
    p20_0 = db.Column(db.Integer)
    p20_1 = db.Column(db.Integer)
    p20_2 = db.Column(db.Integer)
    p20_3 = db.Column(db.Integer)
    p21_0 = db.Column(db.Integer)
    p21_1 = db.Column(db.Integer)
    p21_2 = db.Column(db.Integer)
    p21_3 = db.Column(db.Integer)
    p22_0 = db.Column(db.Integer)
    p22_1 = db.Column(db.Integer)
    p22_2 = db.Column(db.Integer)
    p22_3 = db.Column(db.Integer)
    p23_0 = db.Column(db.Integer)
    p23_1 = db.Column(db.Integer)
    p23_2 = db.Column(db.Integer)
    p23_3 = db.Column(db.Integer)
    p24_0 = db.Column(db.Integer)
    p24_1 = db.Column(db.Integer)
    p24_2 = db.Column(db.Integer)
    p24_3 = db.Column(db.Integer)
    p25_0 = db.Column(db.Integer)
    p25_1 = db.Column(db.Integer)
    p25_2 = db.Column(db.Integer)
    p25_3 = db.Column(db.Integer)
    p26_0 = db.Column(db.Integer)
    p26_1 = db.Column(db.Integer)
    p26_2 = db.Column(db.Integer)
    p26_3 = db.Column(db.Integer)
    p27_0 = db.Column(db.Integer)
    p27_1 = db.Column(db.Integer)
    p27_2 = db.Column(db.Integer)
    p27_3 = db.Column(db.Integer)
    p28_0 = db.Column(db.Integer)
    p28_1 = db.Column(db.Integer)
    p28_2 = db.Column(db.Integer)
    p28_3 = db.Column(db.Integer)
    p29_0 = db.Column(db.Integer)
    p29_1 = db.Column(db.Integer)
    p29_2 = db.Column(db.Integer)
    p29_3 = db.Column(db.Integer)
    p30_0 = db.Column(db.Integer)
    p30_1 = db.Column(db.Integer)
    p30_2 = db.Column(db.Integer)
    p30_3 = db.Column(db.Integer)
    p31_0 = db.Column(db.Integer)
    p31_1 = db.Column(db.Integer)
    p31_2 = db.Column(db.Integer)
    p31_3 = db.Column(db.Integer)
    p32_0 = db.Column(db.Integer)
    p32_1 = db.Column(db.Integer)
    p32_2 = db.Column(db.Integer)
    p32_3 = db.Column(db.Integer)
    p33_0 = db.Column(db.Integer)
    p33_1 = db.Column(db.Integer)
    p33_2 = db.Column(db.Integer)
    p33_3 = db.Column(db.Integer)
    p34_0 = db.Column(db.Integer)
    p34_1 = db.Column(db.Integer)
    p34_2 = db.Column(db.Integer)
    p34_3 = db.Column(db.Integer)
    p35_0 = db.Column(db.Integer)
    p35_1 = db.Column(db.Integer)
    p35_2 = db.Column(db.Integer)
    p35_3 = db.Column(db.Integer)
    p36_0 = db.Column(db.Integer)
    p36_1 = db.Column(db.Integer)
    p36_2 = db.Column(db.Integer)
    p36_3 = db.Column(db.Integer)
    p37_0 = db.Column(db.Integer)
    p37_1 = db.Column(db.Integer)
    p37_2 = db.Column(db.Integer)
    p37_3 = db.Column(db.Integer)
    p38_0 = db.Column(db.Integer)
    p38_1 = db.Column(db.Integer)
    p38_2 = db.Column(db.Integer)
    p38_3 = db.Column(db.Integer)
    p39_0 = db.Column(db.Integer)
    p39_1 = db.Column(db.Integer)
    p39_2 = db.Column(db.Integer)
    p39_3 = db.Column(db.Integer)
    p40_0 = db.Column(db.Integer)
    p40_1 = db.Column(db.Integer)
    p40_2 = db.Column(db.Integer)
    p40_3 = db.Column(db.Integer)
    p41_0 = db.Column(db.Integer)
    p41_1 = db.Column(db.Integer)
    p41_2 = db.Column(db.Integer)
    p41_3 = db.Column(db.Integer)
    p42_0 = db.Column(db.Integer)
    p42_1 = db.Column(db.Integer)
    p42_2 = db.Column(db.Integer)
    p42_3 = db.Column(db.Integer)
    p43_0 = db.Column(db.Integer)
    p43_1 = db.Column(db.Integer)
    p43_2 = db.Column(db.Integer)
    p43_3 = db.Column(db.Integer)
    p44_0 = db.Column(db.Integer)
    p44_1 = db.Column(db.Integer)
    p44_2 = db.Column(db.Integer)
    p44_3 = db.Column(db.Integer)
    p45_0 = db.Column(db.Integer)
    p45_1 = db.Column(db.Integer)
    p45_2 = db.Column(db.Integer)
    p45_3 = db.Column(db.Integer)
    p46_0 = db.Column(db.Integer)
    p46_1 = db.Column(db.Integer)
    p46_2 = db.Column(db.Integer)
    p46_3 = db.Column(db.Integer)
    p47_0 = db.Column(db.Integer)
    p47_1 = db.Column(db.Integer)
    p47_2 = db.Column(db.Integer)
    p47_3 = db.Column(db.Integer)
    p48_0 = db.Column(db.Integer)
    p48_1 = db.Column(db.Integer)
    p48_2 = db.Column(db.Integer)
    p48_3 = db.Column(db.Integer)

    def __init__(self, id):
        self.id = id

    def __repr__(self):
        return 'Stimmen {}>'.format(self.id)